export const expensesTypes = {
  //GET_EXPENSES: 'GET_EXPENSES',
  ADD_EXPENSE: 'ADD_EXPENSE',
  REMOVE_EXPENSE: 'REMOVE_EXPENSE',
  SELECT_EXPENSE: 'SELECT_EXPENSE',
  FILTER_EXPENSES: 'FILTER_EXPENSES'
};
